name: Build README.md

on:
  schedule:
    - cron: '0 16 * * *'
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - run: npm install
        env:
          CI: true

      - name: Update README
        run: |
          set -e
          node updateREADME.js
          cat README.md

      - name: Commit and push if changed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "ronny1020@gmail.com"
          git config --global user.name "README-bot"
          git add README.md
          git diff --staged --quiet || (
            git commit -m "Update README.md"
            git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:master
          )
